FROM elixir:1.8

MAINTAINER Areski <areski@gmail.com>

ENV REFRESHED_AT 2019-03-06

# Install hex
RUN /usr/local/bin/mix local.hex --force && \
    /usr/local/bin/mix local.rebar --force && \
    /usr/local/bin/mix hex.info

WORKDIR /app
COPY . .

RUN mix deps.get

CMD ["bash"]