FROM jessie_elixir110
# replaced by custom image using Jessie
FROM elixir:1.9.4


MAINTAINER Areski <areski@gmail.com>

ENV REFRESHED_AT 2019-06-28

# Install hex
RUN /usr/local/bin/mix local.hex --force && \
    /usr/local/bin/mix local.rebar --force && \
    /usr/local/bin/mix hex.info

WORKDIR /app
COPY . .

RUN mix deps.get

CMD ["bash"]